[versions]
agp = "8.7.0"
kotlin = "2.0.20"

[libraries]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

